let batton = document.querySelector(".bttn");
let jj = document.querySelector(".bttn");
let lavha = document.querySelector(".headline");
let doira = document.querySelector(".circle");
let p = document.querySelector("p");
let back = document.querySelector("body");
let h2 = document.querySelector(".head2");
let div = document.querySelector(".box");
let div3 = document.querySelector(".box12");
let div4 = document.querySelector(".box3");
let div5 = document.querySelector(".box4");
let son1 = document.querySelector(".h21");
let son2 = document.querySelector(".h22");
let son3 = document.querySelector(".h24");
let son4 = document.querySelector(".h25");
let follower = document.querySelector(".subscribe");
let follower1 = document.querySelector(".subscribe1");
let follower2 = document.querySelector(".subscribe2");
let follower3 = document.querySelector(".subscribe");

batton.addEventListener( "click", function(){
    jj.classList.toggle("btn");
    lavha.classList.toggle("swift");
    doira.classList.toggle("move");
    p.classList.toggle("uchun");
    back.classList.toggle("orqa");
    lavha.classList.toggle("rang");
    h2.classList.toggle("clor");
    div.classList.toggle("ground");
    div3.classList.toggle("ground1");
    div4.classList.toggle("ground2");
    div5.classList.toggle("ground3");
    son1.classList.toggle("font1");
    son2.classList.toggle("font2");
    son3.classList.toggle("font3");
    son4.classList.toggle("font4");
    son5.classList.toggle("font5");
    follower.classList.add("word");
    follower1.classList.add("word1");
    follower2.classList.add("word2");
    follower3.classList.add("word3");
});
